global using StandardLevelScenesTransitionSetupDataSO = StandardLevelScenesTransitionSetupData;
global using MultiplayerLevelScenesTransitionSetupDataSO = MultiplayerLevelScenesTransitionSetupData;
global using FeatureAsyncInstaller = BGLib.AppFlow.Initialization.FeatureAsyncInstaller;
